sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tShQdXu2cBUELnLPDpH
    access-key-secret: 2VlFu5ZU6rMixpcMLBFC2RnuP9Oj1S
    bucket-name: sky-itcast-zjl
